### ISSUE TITLE
UI broken when drawing an ellipse

### ISSUE THREAD

**Issue by webbeee** [akiraux/Akira#313] opened 2020-03-30 00:31 UTC
## Current Behavior
Whenever I begin drawing multiple ellipse(s?) (unsure what the plural form of it is) the UI begins breaking down and glitching out.
Example: The headerbar going black after selecting a button.

## Expected Behavior
It should not happen. I don't really know how to get more detailed than that.

## Steps to Reproduce (for bugs)
1. Create an artboard.
2. Draw multiple ellipse(s?).

## Screenshot and Video of the Problem
- https://twitter.com/actuallywebbeee/status/1244385060482056194?s=20
- https://www.youtube.com/watch?v=lbRpCYEU4U4&feature=youtu.be

## Environment Information
- Linux sebastian-desktop 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- NAME="elementary OS"
- VERSION="5.1.2 Hera"
- ID=elementary
- ID_LIKE=ubuntu
- PRETTY_NAME="elementary OS 5.1.2 Hera"
- LOGO=distributor-logo
- VERSION_ID="5.1.2"
- HOME_URL="https://elementary.io/"
- SUPPORT_URL="https://elementary.io/support"
- BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
- PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
- VERSION_CODENAME=hera
- UBUNTU_CODENAME=bionic

## Hardware Info
- AMD FX(tm)-6300 Six-Core Processor × 3
- NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)
- 8.2 GB memory

## Other Information
- Gtk Version: 3.22.30
- DE: Pantheon
- WM: Mutter(Gala)

- Akira Version: Whatever I cloned from the master branch

**Comment by Alecaddd** [comment] 2020-03-30 01:06
Hi, thank you so much for trying Akira and for the detailed bug report.
I tested it on 2 computers and I can't really reproduce the issue, but from the behaviour it seems to be related to your NVIDIA driver as I've had these visual glitches before with other apps.
I'm running version 440.64, which version are you running?

**Comment by webbeee** [comment] 2020-03-30 01:20
Of all the things I don't know how to do its find the version of my NVIDIA driver. Haha
Would you mind explaining how to check?

**Comment by Alecaddd** [comment] 2020-03-30 01:34
The proprietary drivers are now part of the official Ubuntu repository, so you should be able to install them, and automatically remove the outdated nouveau drivers with the `sudo ubuntu-drivers autoinstall` command.
More info here: https://linuxconfig.org/how-to-install-the-nvidia-drivers-on-ubuntu-18-04-bionic-beaver-linux

**Comment by webbeee** [comment] 2020-03-30 01:51
Alright, I installed it and rebooted. The driver version is 435.21.
And yes, I am still experiencing the issue.

**Comment by albfan** [comment] 2020-03-30 07:42
Can you run akira with debug and attach here the log:

    com.github.akiraux.akira --gtk-debug=all --gtk-no-debug=layout,interactive,resize --gdk-debug=all &> akira.log

That command may explain what is happening. Do that glitches happens in other apps?

**Comment by webbeee** [comment] 2020-04-01 00:02
[akira.log](https://github.com/akiraux/Akira/files/4412050/akira.log)
No, it only happens with Akira.

**Comment by Alecaddd** [comment] 2020-08-14 16:37
@webbeee does this issue persist with the recent changes?

**Comment by webbeee** [comment] 2020-08-15 19:37
Nope, it doesn't seem too.

**Comment by albfan** [comment] 2020-08-15 20:45
thanks for reporting. Closing the issue

**Closed by albfan** 2020-08-15 20:45 UTC
