### ISSUE TITLE
Akira Templates

### ISSUE THREAD

**Issue by Malsasa** [akiraux/Akira#347] opened 2020-06-09 03:59 UTC
Hello, I found Akira after I installed it with Snap on Ubuntu 20.04 and it is amazing. I think it would be great for all users if Akira ships with editable examples or templates by default. I think this would attracts people who are getting started to UI/UX design. For example, when opening Akira, user may click **Examples** button, and see choices of UI examples. Picture below depicts my idea better. Thank you. 

![Qt Creator showing its user interface examples](https://1.bp.blogspot.com/-dDujVO0ote0/XXHYR7nCA-I/AAAAAAAAXiI/PX5X-SDQkI0yeV-d81CrhW6flqCzX-YzACK4BGAYYCw/s640/Screenshot_20190905_172438.png)

Regards,

Ade

**Comment by abienz** [comment] 2020-06-09 14:33
It's an interesting idea,

Perhaps there could be options to have a template with standard Android or standard iOS UI features added as standard, Perhaps some standard Web UI layouts like Hero, 3 Column, Footer would be good for desktop too.

Another similar feature I would like to see, is when creating Artboards you would have an option to pick from standard device sizes, Figma and Sketch currently have this feature where you can pick from common iPhone and Android device sizes, or common desktop/laptop screen sizes.

**Comment by Alecaddd** [comment] 2020-06-09 23:55
Indeed, this is something we're considering and we will implement in the future.
I'm gonna close this bug since it's a duplicate of #63 
Thank you for trying Akira.

**Closed by Alecaddd** 2020-06-09 23:55 UTC
