### ISSUE TITLE
save Designing

### ISSUE THREAD

**Issue by mbfakourii** [akiraux/Akira#452] opened 2020-10-17 11:19 UTC
Hi I can not save anything I have an error in Akira
```
(Akira:21439): GLib-GIO-WARNING **: 14:45:55.443: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)

(Akira:21439): Gtk-WARNING **: 14:45:55.543: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

```

or open
```
(Akira:21439): GLib-GIO-WARNING **: 14:49:20.123: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)

(Akira:21439): Gtk-WARNING **: 14:49:20.187: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

```

my os
Xubuntu 20.04

**Comment by Alecaddd** [comment] 2020-10-25 20:02
Which version of Akira are you using?
Did you compile it from source or you installed the Flatpak or Snap version?

**Comment by mbfakourii** [comment] 2020-10-26 05:36
version v0.0.13 - alpha
and i install from Snap

**Comment by Alecaddd** [comment] 2020-10-26 17:35
This is a duplicate of #419

**Closed by Alecaddd** 2020-10-26 17:35 UTC
