### ISSUE TITLE
Akira cannot save files

### ISSUE THREAD

**Issue by yasharya2901** [akiraux/Akira#419] opened 2020-08-23 11:40 UTC
## Expected Behavior

Akira should save the file in the given location.

## Current Behavior

I was trying to save the session by simply clicking the Save button and saved it to a folder but the folder was empty. So, I saved it again using Save As in the same folder but this time, I added .akira in the last but when I try to open it, nothing happened. Also, when I double-clicked the saved file, it opened with errors in Text Editors.

## Steps to Reproduce (for bugs)

1. Click the Save button and specify the name and location.
2. Click on Save
3. Click on Save As
4. Write .akira after the name and then Save again. 

## Screenshots of the Problem
 

Video Link - https://drive.google.com/file/d/1ut4hrdoWdHRWVup5arLYDa971jVcxUAo/view?usp=sharing

## Your Environment (for bugs)

- Akira Version: v0.0.12 - alpha (downloaded from Ubuntu Software Center)
- OS Info: Ubuntu 20.04.1

The command result:
Linux yash-VPCEH38FN 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by albfan** [comment] 2020-08-23 16:59
Please provide a stacktrace if possible.

Keep in mind this is a beta release so broken things are expected.

**Comment by yasharya2901** [comment] 2020-08-23 17:49
Yeah, that's why I reported it.

**Comment by Alecaddd** [comment] 2020-08-23 23:19
If you downloaded it from the Ubuntu software center it might be an issue with the snap package.
I'll ping @popey in case he has any free time to double check this.

**Comment by yasharya2901** [comment] 2020-08-26 16:35
Any update on this? @Alecaddd

**Comment by albfan** [comment] 2020-08-27 00:23
I can confirm this issue, seems to be general on flatpak and host too.

My saved files are 1 byte.

**Comment by yasharya2901** [comment] 2020-08-27 19:40
There you go!
[bug.zip](https://github.com/akiraux/Akira/files/5138449/bug.zip)

**Comment by albfan** [comment] 2020-08-28 13:15
```
$ unzip -l ~/Descargas/bug.akira 
Archive:  /home/alberto/Descargas/bug.akira
warning [/home/alberto/Descargas/bug.akira]:  zipfile is empty
```

I think snap is getting in the way somehow.

It is expected that a correct file has a content.json file inside

**Comment by albfan** [comment] 2020-09-27 11:15
Can you revisit this, seems new changes landed on snap definition

**Comment by yasharya2901** [comment] 2020-09-28 04:01
> Can you revisit this, seems new changes landed on snap definition

The problem still remains.

**Comment by mbfakourii** [comment] 2020-10-26 17:44
Is the problem still unresolved?

**Comment by Alecaddd** [comment] 2020-10-26 17:45
I'm working on it, it's an I/O problem with a missing plug in the snapcraft.
I'm testing it locally and I'll submit a patch soon.

**Comment by mbfakourii** [comment] 2020-10-26 17:49
@Alecaddd tanks

**Comment by Alecaddd** [comment] 2020-10-26 19:35
Here's the terminal error when trying to save a file from the Snap version:

```
(Akira:15419): Akira-WARNING **: 12:26:14.495: ZipArchiveHandler.vala:94:
Error creating directory /run/user/1000/doc/cdadaa7d/.~lock.akira.test.akira: Operation not permitted
```

This is probably due to the fact that we're trying to create the hidden `.~lock` file when saving and opening a file, which is basically the opened ZIP archive of our `.akira` file.
Since the snap is currently in `confinement: strict`, we need to specify the proper permissions and interfaces we want to give write/read access.

This is what I tried to do:
```YML
plugs:
  dot-akira:
    interface: personal-files
    read:
    - $HOME/.akira
    - $HOME/.lock
    write:
    - $HOME/.akira
    - $HOME/.lock
```

And then I added the `dot-akira` to the list of plugs.
No luck so far, unfortunately, as the problem persists.
Pinging @popey hoping he can shed some light on this.
I will keep trying anyway.

**Comment by Alecaddd** [comment] 2020-10-26 20:22
I also tried to manually enable the connection with `sudo snap connect akira:do-akira`, but nothing changed.
What's interesting is that, even if I was trying to save the file into `HOME/Documents/`, the error reported this directory: `/run/user/1000/doc/cdadaa7d/.lock.akira.test.akira`

I wonder if it's an issue in our implementation of GLib, which gets the parent directory of the selected file, but since we're confined inside a snap, the directory is not what the user selected.

**Comment by Alecaddd** [comment] 2020-10-27 06:02
It seems that something is not right with the `Gtk.FileChooser`
https://github.com/akiraux/Akira/blob/697c97774184a90714abe0f54fbc3e4c432e99be/src/FileFormat/FileManager.vala#L85-L87

The `get_path ()` of the selected file returns this path `/run/user/1000/doc/3e6d23ed` instead of the actual location where the user wants to save the file.

**Comment by Lin-Buo-Ren** [comment] 2020-10-27 07:38
I wonder if it's possible to use the path under /tmp for the temporary file instead since snap applications can freely access its (though isolated) private /tmp directory.

**Closed** 2021-07-21 04:14 UTC
Labels: Snap

**Comment by LucileDT** [comment] 2021-07-27 11:50
Closing as Snapcraft packaging and release automation is removed due to lack of active maintainers in the team.

**Comment by patreeceeo** [comment] 2022-05-04 22:46
I'm seeing what looks like the same or similar bug with the version I just installed with flatpak. Shall I open a new issue?

**Comment by Alecaddd** [comment] 2022-05-04 23:17
We're reworking the architecture of akira from scratch in the `main` branch, which will take care of these issues.
The master branch, and consequentially the flatpak version, are bit stale at the moment.
