### ISSUE TITLE
Unable to build latest Akira from source

### ISSUE THREAD

**Issue by alcomposer** [akiraux/Akira#177] opened 2019-06-10 11:01 UTC
- Akira Version:7f24f54
- OS Info:Arch(up-to-date)

### Issue:
Unable to build Akira from source:

```
[1/44] Compiling Vala source ../src/Main.vala ../src/Application.val... ../src/Lib/Item.vala ../src/Lib/Selection/Nob.vala src/config.vala.
FAILED: src/25a6634@@com.github.akiraux.akira@exe/Main.c src/25a6634@@com.github.akiraux.akira@exe/Application.c src/25a6634@@com.github.akiraux.akira@exe/Window.c src/25a6634@@com.github.akiraux.akira@exe/FileFormat/AkiraFile.c src/25a6634@@com.github.akiraux.akira@exe/FileFormat/JsonObject.c src/25a6634@@com.github.akiraux.akira@exe/FileFormat/JsonObjectArray.c src/25a6634@@com.github.akiraux.akira@exe/FileFormat/ZipArchiveHandler.c src/25a6634@@com.github.akiraux.akira@exe/FileFormat/Objects/Version.c src/25a6634@@com.github.akiraux.akira@exe/Services/Settings.c src/25a6634@@com.github.akiraux.akira@exe/Services/ActionManager.c src/25a6634@@com.github.akiraux.akira@exe/Services/EventBus.c src/25a6634@@com.github.akiraux.akira@exe/Utils/Dialogs.c src/25a6634@@com.github.akiraux.akira@exe/Utils/BlendingMode.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/HeaderBar.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/LeftSideBar.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/MainCanvas.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/MainWindow.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/RightSideBar.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/Partials/LayersPanel.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/Partials/PagesPanel.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/Partials/Artboard.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/Partials/Layer.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/Partials/FillsBoxPanel.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/Partials/FillItem.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/Partials/BlendingModeItem.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/Partials/TransformPanel.c src/25a6634@@com.github.akiraux.akira@exe/Layouts/Partials/AlignItemsPanel.c src/25a6634@@com.github.akiraux.akira@exe/Partials/HeaderBarButton.c src/25a6634@@com.github.akiraux.akira@exe/Partials/MenuButton.c src/25a6634@@com.github.akiraux.akira@exe/Partials/ZoomButton.c src/25a6634@@com.github.akiraux.akira@exe/Partials/ButtonImage.c src/25a6634@@com.github.akiraux.akira@exe/Partials/AlignBoxButton.c src/25a6634@@com.github.akiraux.akira@exe/Partials/LinkedInput.c src/25a6634@@com.github.akiraux.akira@exe/Partials/PanelSeparator.c src/25a6634@@com.github.akiraux.akira@exe/Partials/PopoverButton.c src/25a6634@@com.github.akiraux.akira@exe/Models/FillsItemModel.c src/25a6634@@com.github.akiraux.akira@exe/Models/FillsListModel.c src/25a6634@@com.github.akiraux.akira@exe/Widgets/SettingsDialog.c src/25a6634@@com.github.akiraux.akira@exe/Lib/Canvas.c src/25a6634@@com.github.akiraux.akira@exe/Lib/Item.c src/25a6634@@com.github.akiraux.akira@exe/Lib/Selection/Nob.c src/25a6634@@com.github.akiraux.akira@exe/config.c 
valac -C --debug --debug --vapidir /home/alexmitchell/Documents/github/Akira/src/vapi --pkg json-glib-1.0 --pkg libarchive --pkg goocanvas-2.0 --pkg cairo --pkg libxml-2.0 --pkg gee-0.8 --pkg granite --pkg gtk+-3.0 --color=always --directory src/25a6634@@com.github.akiraux.akira@exe --basedir ../src --gresources=../data/assets.gresource.xml ../src/Main.vala ../src/Application.vala ../src/Window.vala ../src/FileFormat/AkiraFile.vala ../src/FileFormat/JsonObject.vala ../src/FileFormat/JsonObjectArray.vala ../src/FileFormat/ZipArchiveHandler.vala ../src/FileFormat/Objects/Version.vala ../src/Services/Settings.vala ../src/Services/ActionManager.vala ../src/Services/EventBus.vala ../src/Utils/Dialogs.vala ../src/Utils/BlendingMode.vala ../src/Layouts/HeaderBar.vala ../src/Layouts/LeftSideBar.vala ../src/Layouts/MainCanvas.vala ../src/Layouts/MainWindow.vala ../src/Layouts/RightSideBar.vala ../src/Layouts/Partials/LayersPanel.vala ../src/Layouts/Partials/PagesPanel.vala ../src/Layouts/Partials/Artboard.vala ../src/Layouts/Partials/Layer.vala ../src/Layouts/Partials/FillsBoxPanel.vala ../src/Layouts/Partials/FillItem.vala ../src/Layouts/Partials/BlendingModeItem.vala ../src/Layouts/Partials/TransformPanel.vala ../src/Layouts/Partials/AlignItemsPanel.vala ../src/Partials/HeaderBarButton.vala ../src/Partials/MenuButton.vala ../src/Partials/ZoomButton.vala ../src/Partials/ButtonImage.vala ../src/Partials/AlignBoxButton.vala ../src/Partials/LinkedInput.vala ../src/Partials/PanelSeparator.vala ../src/Partials/PopoverButton.vala ../src/Models/FillsItemModel.vala ../src/Models/FillsListModel.vala ../src/Widgets/SettingsDialog.vala ../src/Lib/Canvas.vala ../src/Lib/Item.vala ../src/Lib/Selection/Nob.vala src/config.vala
../src/FileFormat/ZipArchiveHandler.vala:268.20-268.86: error: 1 extra arguments for `Archive.Result Archive.Read.read_data_block (out weak uint8[], out Archive.int64_t)'
            while (archive.read_data_block (out buffer, out buffer_length, out offset) == Archive.Result.OK) {
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/FileFormat/ZipArchiveHandler.vala:269.49-269.54: error: Argument 1: Cannot convert from `void*' to `unowned uint8[]'
                if (extractor.write_data_block (buffer, buffer_length, offset) != Archive.Result.OK) {
                                                ^^^^^^
../src/FileFormat/ZipArchiveHandler.vala:269.21-269.78: error: 1 extra arguments for `ssize_t Archive.Write.write_data_block (uint8[], Archive.int64_t)'
                if (extractor.write_data_block (buffer, buffer_length, offset) != Archive.Result.OK) {
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/FileFormat/ZipArchiveHandler.vala:319.37-319.57: error: Argument 1: Cannot convert from `int64' to `Archive.int64_t'
                    entry.set_size (file_info.get_size ());
                                    ^^^^^^^^^^^^^^^^^^^^^
../src/FileFormat/ZipArchiveHandler.vala:320.41-320.60: error: Argument 1: Cannot convert from `uint' to `Archive.FileType'
                    entry.set_filetype ((uint) Posix.S_IFREG);
                                        ^^^^^^^^^^^^^^^^^^^^
../src/FileFormat/ZipArchiveHandler.vala:336.25-336.63: error: 1 extra arguments for `ssize_t Archive.Write.write_data (uint8[])'
                        archive.write_data (buffer, bytes_read);
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 6 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

**Comment by bilelmoussaoui** [comment] 2019-06-10 11:23
Duplicate of  https://github.com/akiraux/Akira/issues/137

**Closed by bilelmoussaoui** 2019-06-10 11:23 UTC
