### ISSUE TITLE
[Question] Why elementary OS?

### ISSUE THREAD

**Issue by AdrianVovk** [akiraux/Akira#176] opened 2019-06-10 06:39 UTC
Why is this app elementary-specific? The elementary themes look absolutely horrible on anything that isn't elementary OS, and trying to replace them with Adwaita and a proper HIG is even more broken. This is less of a GTK app and more of an elementary app... Why are you limiting this app to look acceptable on just one distribution?

**Comment by albfan** [comment] 2019-06-10 07:35
You can try to run from flatpak, which should give you a native elementary OS theme on any distro

**Comment by AdrianVovk** [comment] 2019-06-10 16:00
@albfan Yes, but it doesn't fit in with any of the other GTK apps.

I guess my question is more about why you chose the elementary HIG over the GNOME HIG?

**Comment by Alecaddd** [comment] 2019-06-10 16:32
Hi @AdrianVovk, thank you so much for your interest in Akira.
We decided to go with the elementary HIG and stylesheet because it's more inline with what we want to achieve with this app.
Having developed elementary OS apps for a couple of years, I always found myself more comfortable and more inline with the decisions and rules laid out in the elementary HIG.
From a merely visual point of view, we think the elementary theme and stylesheet brings more depth and consistency than other themes.

The reason why we won't allow the distribution to style the app is to prevent unexpected issues and bugs that we can't control. Controlling the narrative and the UI/UX of the final product is vital for us in order to prevent bugs and visual inconsistencies across distributions that we can't fix.

I'm curious to hear your point of view. What's so horrible about the elementary HIG?
Cheers

**Comment by AdrianVovk** [comment] 2019-06-10 18:55
I agree that distributions shouldn't theme apps. I'm developing a distribution myself and my concern is that Akira will only truly look fully native on elementary OS. There are just simply more DEs and distros built around the GNOME HIG. Fedora, RHEL, Ubuntu, Solus (Budgie and the GNOME spin), and even Deepin to some extent. The only OS that follows elementary HIG is elementary. GNOME apps look consistent and that's what makes them great. All of the GTK themes are also built with GNOME HIG in mind, and elementary apps look seriously broken with anything but the elementary theme. While distros shouldn't theme apps, *users should be able to*.

Here's GNOME apps next to elementary apps (scaled in my DE's overview).
![screenshot](https://user-images.githubusercontent.com/11251606/59216890-b3cfd280-8b8a-11e9-84e5-13ed10d28622.png)
They don't look too dissimilar (mostly because SpiceUp uses a dark theme), but some key factors like the close/minimize/maximize buttons are different. They don't respect the system light/dark mode settings. Titles are a lot smaller than in other apps. These apps *look* like they are made for a different OS, *which they are.* This would all be fine and great if these weren't GTK apps. These apps could have looked perfectly native on most platforms, but they only fully fit in with the rest of the DE on elementary.

**Comment by johnfactotum** [comment] 2019-06-12 02:40
Please consider supporting just one theme in addition to elementary: Adwaita.

- Adwaita is not just any theme. It's part of GTK itself as the default and fallback. Most third-party themes and other tools will be be largely compatible with Adwaita.
- Don't support third-party themes. You can say: issues caused by third-party themes are invalid, we only support elementary and Adwaita. In my opinion this would add minimum additional burden on development, while providing much, much greater compatibility for most platforms' and users' needs.
- elementary and GNOME's HIGs don't differ *that* much. For applications, the single most prominent difference is probably just non-symbolic vs. non-symbolic icons. This and other small differences can be easily made user-configurable, or the app can apply different styles for different themes.

I understand that supporting different themes is not easy, but considering that it uses GTK, and the fact that elementary's and GNOME's HIG and technical stack are already very closely aligned (as opposed to that of, say, KDE, which is entirely different), it would really be a shame if it can't fit in just as well in GNOME, Budgie, and other GTK desktop environments.

**Comment by BonkeDyan** [comment] 2019-06-12 09:45
I am trying to install depencies on Elementary os Juno so that i can compile the app hence it's still on development stages. Is there a tutorial set on how to install listed dependencies?

**Comment by albfan** [comment] 2019-06-12 10:34
@BonkeDyan please see #30. You can run under flatpak without effort. flatpak json manifest should show you the dependencies. They can or cannot be in package manager for elementary OS

**Comment by bilelmoussaoui** [comment] 2019-06-30 07:45
Sorry, but we don't have any plans to support any GTK theme at all. Such app, need to have its own theme shipped within it. Things might or might not change in the future, whatever happens, we will keep you up to date.
For now, I'm going to close this issue. If you have any concerns, you can always comment/reopen this.

**Closed by bilelmoussaoui** 2019-06-30 07:45 UTC

**Comment by AdrianVovk** [comment] 2019-06-30 17:21
@bilelmoussaoui As mentioned earlier, Adwaita is less of a GTK theme than elementary is, because Adwaita is built into GTK, whereas elementary is some css that extends Adwaita.

However, if you don't want to support it, I'll respect the decision

**Comment by bilelmoussaoui** [comment] 2019-06-30 19:01
That's something I'm aware of. We have just went with elementary theme only for now, as I have said before, things might or might not change, we will keep you up to date.

**Comment by ripefig** [comment] 2019-07-14 08:51
I'd chip in to fund the developement of this app, but for me the Elementary theme is a deal breaker.

So I definitely second the request to support Adwaita and Gnome HIG, though it may be hard given your choice of a relatively esoteric platform (EOS). 

Gnome has many more users than Elementary and and apps that use Adwaita are generally themable, since third-party themes take Adwaita as the starting point. For example KDE users will be able to theme it with the Breeze style (or any other cross platform theme), instead of having your app look like this:

![image](https://user-images.githubusercontent.com/45201036/61181220-e195b480-a62b-11e9-9361-44ae677b9470.png)

EOS is a very minor platform and it resides in a world of its own, separate from the rest of the GTK ecosystem. Elementary theme is incompatible with the rest of GTK. GTK CSD-style apps are small in number, and fragmenting this tiny slice of the ecosystem between Elementary and Gnome is not desirable.

**Comment by bilelmoussaoui** [comment] 2019-07-14 10:26
The issue you're reporting is not related to this application at all. It's a known reported issue on the baseApp this application and Sequeler uses for Flatpak (that I maintain) and I have reported that upstream to get that fixed.

**Comment by ripefig** [comment] 2019-07-14 10:29
All Elemntary apps are like this on KDE, it's a platform issue not a sequeler issue.

**Comment by ripefig** [comment] 2019-08-31 10:16
@bilelmoussaoui the issue would be largely resolved as far as Gnome/EOS is concerned if Elementary augmented the Adwaita stylesheet so that it could theme Granite. For 100% consistency you'd also have to two layouts and two sets of icon definitions. Maybe talk to them and try to persuade them to this? The fragmentation of GTK caused by the Gnome/EOS split is really senseless and really bad for apps.

**Comment by myfreeweb** [comment] 2020-08-26 15:48
> For applications, the single most prominent difference is probably just non-symbolic vs. non-symbolic icons

(well, "non-" twice aside) looks like Akira already has a symbolic icons toggle in the settings even.

The big bug on Adwaita right now is white text on a light background in a sidebar. Also some icons are missing.
